from pathlib import Path
import pandas as pd
out=Path(__file__).resolve().parent
s=pd.read_csv(out/'cone25_vs_cone30_summary.csv')
r=pd.read_csv(out/'wallon_8p333_window_summary.csv')
late=r.iloc[-1]
text=f'''\n\n## Cone25 decision addendum\n\nThe authorized cone25 run completed at 8.333 ms and was post-processed with the same 50 µs telemetry/ODB cadence and exact SmoothWall114 triangle audit. The comparison is in `cone25_vs_cone30_summary.csv`.\n\n- Cone30 baseline robot arc change: **{s.iloc[0].robot_delta_mm:.4f} mm**; cone25: **{s.iloc[1].robot_delta_mm:.4f} mm** (both negative, so the motion remains reverse in the canonical arc convention).\n- Mean tangential speed proxy: cone30 {s.iloc[0].mean_Vt_mm_s:.4f} mm/s; cone25 {s.iloc[1].mean_Vt_mm_s:.4f} mm/s.\n- True-axis UR ranges (cone25): UR1 {s.iloc[1].UR1_range_rad:.3f} rad, UR2 {s.iloc[1].UR2_range_rad:.3f} rad, UR3 {s.iloc[1].UR3_range_rad:.3f} rad.\n- Exact minimum gap: cone30 {s.iloc[0].min_exact_gap_um:.3f} µm; cone25 {s.iloc[1].min_exact_gap_um:.3f} µm. Both remain below zero; cone25 is not a no-penetration pass.\n- Aggregate CPRESS: cone30 {s.iloc[0].max_CPRESS_MPa:.3f} MPa; cone25 {s.iloc[1].max_CPRESS_MPa:.3f} MPa.\n- Cone25 late post-impact window: phase-equivalent rate {late.f_robot_phase_equiv_Hz:.3f} Hz, R={late.R_phase_vs_30:.3f}, wobble RMS {late.omega_wobble_rms_rad_s:.3f} rad/s; classification remains **B_SUSTAINED_POST_IMPACT_NONMAGNETIC_ROTATIONAL_STALL**.\n\nConclusion: reducing cone30 to cone25 did not remove the geometric wedge or restore forward motion. It slightly increased the reverse arc excursion and made the exact minimum gap more negative, although CPRESS decreased modestly. The zero-cost map's cylinder sanity limit (~23°) explains why 25° can still enter the constrained region once translation and transverse offset are included. No further cone-angle or contact tuning is authorized by this stage; the next action should be selected from the mechanism classification, not from a claim that cone25 solved the jam.\n'''
p=out/'Wobble30Hz_wallon_8p333_rotational_load_report.md'; p.write_text(p.read_text(encoding='utf-8')+text,encoding='utf-8')
(out/'cone25_decision.md').write_text(text,encoding='utf-8')
